server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://j7b305.p.ssafy.io:8761/eureka
      #defaultZone: http://localhost:8761/eureka

spring:
  # bean중복 에러 해결
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**
            - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: festival-service
          uri: lb://FESTIVAL-SERVICE
          predicates:
            - Path=/api/festival-service/**
            - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

        - id: main-service
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/api/main-service/**
            - Method=GET,POST,PUT,DELETE
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}
        -
        - id: recomm-service
          uri: lb://RECOMM-SERVICE
          predicates:
            - Path=/api/recomm-service/**
            - Method=GET,POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/auth-service/(?<segment>.*),/$\{segment}

token:
  secret: secretKey
  refresh: refreshKey
